# Generated by Django 3.0.3 on 2020-06-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HirarID', models.IntegerField()),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('TransactionPIN', models.CharField(blank=True, max_length=30, null=True)),
                ('MobileNumber', models.BigIntegerField()),
                ('Role', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=300)),
                ('Email', models.CharField(max_length=300)),
                ('District', models.CharField(max_length=300)),
                ('AdhaarID', models.CharField(max_length=300)),
                ('PIN', models.CharField(max_length=300)),
                ('State', models.CharField(max_length=300)),
                ('Country', models.CharField(max_length=300)),
                ('isactive', models.BooleanField()),
                ('ispayed', models.BooleanField()),
                ('KYC', models.BooleanField()),
                ('NumberOfAccounts', models.IntegerField()),
                ('AmountWithdrawed', models.IntegerField()),
                ('TotalMoney', models.IntegerField()),
                ('ReferenceID', models.CharField(blank=True, max_length=30, null=True)),
                ('ReferalID', models.CharField(blank=True, max_length=30, null=True)),
                ('CreationDate', models.DateField(blank=True, null=True)),
                ('PaystartDate', models.DateField(blank=True, null=True)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='UsersPhoto')),
                ('DateOfBirth', models.TextField(blank=True, max_length=300, null=True)),
                ('MaritalStatus', models.TextField(blank=True, max_length=300, null=True)),
                ('NomineeName', models.TextField(blank=True, max_length=300, null=True)),
                ('NomineeRelation', models.TextField(blank=True, max_length=300, null=True)),
                ('BankName', models.TextField(blank=True, max_length=300, null=True)),
                ('BankBranch', models.TextField(blank=True, max_length=300, null=True)),
                ('AccountNummber', models.TextField(blank=True, max_length=300, null=True)),
                ('IFSCcode', models.TextField(blank=True, max_length=300, null=True)),
                ('PANNumber', models.TextField(blank=True, max_length=300, null=True)),
                ('FatherName', models.TextField(blank=True, max_length=300, null=True)),
                ('Adhaar_Front', models.ImageField(blank=True, null=True, upload_to='UsersPhoto')),
                ('Adhaar_Back', models.ImageField(blank=True, null=True, upload_to='UsersPhoto')),
                ('PANCard', models.ImageField(blank=True, null=True, upload_to='UsersPhoto')),
                ('Passbook', models.ImageField(blank=True, null=True, upload_to='UsersPhoto')),
            ],
        ),
    ]
