# Generated by Django 3.0.3 on 2020-06-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserMobile', models.IntegerField()),
                ('UserBalanceHirar', models.IntegerField()),
                ('BalanceAdded', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Withdraws',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserMobile', models.IntegerField()),
                ('WithdrawAmount', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('WithdrawRequestDate', models.DateField()),
                ('WithdrawFullfilledDate', models.DateField()),
            ],
        ),
    ]
