# Generated by Django 3.0.3 on 2020-06-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_balancehistory_withdraws'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraws',
            name='WithdrawFullfilledDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
