# Generated by Django 3.0.3 on 2020-06-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20200610_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraws',
            name='WithdrawAmount',
            field=models.IntegerField(),
        ),
    ]
