# Generated by Django 3.0.3 on 2020-06-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_epin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epin',
            name='To',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
