# Generated by Django 3.0.3 on 2020-06-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20200615_2216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EPIN',
            new_name='EPINRequest',
        ),
    ]
