# Generated by Django 3.0.3 on 2020-06-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20200615_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='epinrequest',
            name='Purpose',
            field=models.CharField(default='Add', max_length=50),
            preserve_default=False,
        ),
    ]
