# Generated by Django 3.0.3 on 2020-06-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_epinrequest_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desc', models.TextField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Offers')),
                ('File', models.FileField(blank=True, null=True, upload_to='Offers')),
            ],
        ),
    ]
