# Generated by Django 3.0.7 on 2020-07-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_deadmoney'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='PaystartDate',
            new_name='lastMoneyAddedDate',
        ),
        migrations.RemoveField(
            model_name='users',
            name='AccountNummber',
        ),
        migrations.AddField(
            model_name='users',
            name='CurrentLevel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='Perdaycost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='TotaldaysLeft',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
