# Generated by Django 3.0.7 on 2020-07-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_auto_20200712_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='NumberOfAccounts',
        ),
        migrations.AddField(
            model_name='users',
            name='AccountNummber',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
