# Generated by Django 3.0.7 on 2020-07-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_auto_20200712_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='NumberOfAccounts',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
