# Generated by Django 3.0.7 on 2020-07-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_auto_20200715_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Perdaycost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
