# Generated by Django 3.0.7 on 2020-07-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_users_perdaycost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Perdaycost',
        ),
    ]
