# Generated by Django 3.0.7 on 2020-07-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_remove_users_perdaycost'),
    ]

    operations = [
        migrations.AddField(
            model_name='epinrequest',
            name='UserName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
