# Generated by Django 3.0.7 on 2020-07-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_epinrequest_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MobileNumber', models.BigIntegerField()),
                ('Desc', models.TextField()),
                ('Header', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('isviewed', models.BooleanField()),
            ],
        ),
    ]
